# Generated by Django 5.0.7 on 2024-08-18 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='course.course'),
        ),
        migrations.AddField(
            model_name='session',
            name='time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
