# Generated by Django 5.1 on 2024-09-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_rate_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
